<?php
/**
 * Homepage copy.
 *
 * Generated by tools/export_home_content.py from the Shopify
 * templates/index.json, so it matches what the storefront rendered. The
 * homepage section was block-driven (25 blocks across
 * 6 types); blocks are grouped by type here, in block_order.
 *
 * Regenerate rather than editing by hand while the Shopify theme is still the
 * source of truth. Once it is not, edit freely and drop the generator.
 *
 * @package Medzuro
 */

defined( 'ABSPATH' ) || exit;

/**
 * Homepage settings and blocks.
 *
 * @return array
 */
function medzuro_home() {
	static $home = null;

	if ( null !== $home ) {
		return $home;
	}

	$home = array(
		'settings' => array(
			'hero_kicker'            => 'Your wellness store in Fiji',
			'hero_heading'           => 'Your wellness store,',
			'hero_accent'            => 'right here in Fiji.',
			'hero_text'              => 'Genuine HolyOak supplements, available locally with same-day delivery across most of Suva and local pickup.',
			'primary_label'          => 'Shop all products',
			'primary_url'            => '/collections/all',
			'secondary_label'        => 'Local pickup & delivery',
			'secondary_url'          => '/pages/delivery',
			'collection'             => 'all',
			'product_limit'          => 5,
			'lab_url'                => '/pages/lab-test-and-purity',
			'phone'                  => '+679-8029-837',
			'products_title'         => 'Best Sellers',
			'product_meta'           => '60 Capsules',
			'show_ratings'           => true,
			'add_label'              => 'Add to cart',
			'soldout_label'          => 'Sold out',
			'show_world'             => true,
			'world_kicker'           => 'HolyOak around the world',
			'world_heading'          => 'Trusted internationally.',
			'world_heading_2'        => 'Now available locally in',
			'world_accent'           => 'Fiji.',
			'show_lab'               => true,
			'lab_kicker'             => 'Quality you can trust',
			'lab_heading'            => 'Lab tested. Proven.',
			'lab_accent'             => 'Trusted.',
			'lab_text'               => 'Every batch of HolyOak supplements is independently tested for purity, potency and safety by Eurofins.',
			'lab_brand'              => 'eurofins',
			'lab_brand_tagline'      => 'The global trusted lab',
			'lab_link_label'         => 'Learn more',
			'reviews_title'          => 'What Fiji Customers Are Saying',
			'show_newsletter'        => true,
			'newsletter_text'        => 'Stay updated with our latest products, offers and wellness tips.',
			'newsletter_placeholder' => 'Enter your email address',
			'newsletter_button'      => 'Subscribe',
		),
		'blocks'   => array(
			'trust'     => array(
				array(
					'icon'  => 'truck',
					'title' => 'Delivered across Fiji',
					'text'  => 'Same-day delivery in most of Suva',
				),
				array(
					'icon'  => 'pin',
					'title' => 'Local pickup',
					'text'  => 'Collect from our Suva location',
				),
				array(
					'icon'  => 'shield',
					'title' => 'Genuine HolyOak',
					'text'  => 'Authentic products you can trust',
				),
				array(
					'icon'  => 'headset',
					'title' => 'Fiji customer support',
					'text'  => 'Call or Viber, we are here for you',
				),
			),
			'stat'      => array(
				array(
					'icon'  => 'globe',
					'value' => '30+',
					'label' => 'Countries',
				),
				array(
					'icon'  => 'users',
					'value' => '2.4M+',
					'label' => 'Products sold worldwide',
				),
				array(
					'icon'  => 'pin',
					'value' => '1',
					'label' => 'Local destination in Fiji',
				),
			),
			'flag'      => array(
				array(
					'flag'  => 'usa',
					'label' => 'USA',
				),
				array(
					'flag'  => 'canada',
					'label' => 'Canada',
				),
				array(
					'flag'  => 'uk',
					'label' => 'UK',
				),
				array(
					'flag'  => 'uae',
					'label' => 'UAE',
				),
				array(
					'flag'  => 'qatar',
					'label' => 'Qatar',
				),
				array(
					'flag'  => 'sa',
					'label' => 'South Africa',
				),
				array(
					'flag'  => 'kenya',
					'label' => 'Kenya',
				),
				array(
					'flag'  => 'europe',
					'label' => 'Europe',
				),
			),
			'lab_check' => array(
				array(
					'icon'  => 'lab',
					'title' => 'Purity Tested',
					'text'  => 'Heavy metals and contaminants',
				),
				array(
					'icon'  => 'puzzle',
					'title' => 'Potency Verified',
					'text'  => 'Active ingredients accurately measured',
				),
				array(
					'icon'  => 'shield',
					'title' => 'Quality Assured',
					'text'  => 'Meets international quality standards',
				),
				array(
					'icon'  => 'package',
					'title' => 'Global Trusted',
					'text'  => 'Eurofins is a global leader in laboratory services',
				),
			),
			'review'    => array(
				array(
					'rating'   => 5,
					'text'     => 'Excellent quality products and fast delivery. I have been using Holyoak supplements for months and feel the difference.',
					'author'   => 'Sarah L.',
					'location' => 'Suva, Fiji',
					'avatar'   => 'sea',
				),
				array(
					'rating'   => 5,
					'text'     => 'Genuine products you can trust. Love that they provide lab test results for purity and quality.',
					'author'   => 'Rajesh K.',
					'location' => 'Nausori, Fiji',
					'avatar'   => 'lagoon',
				),
				array(
					'rating'   => 5,
					'text'     => 'Same-day delivery in Suva is a game changer. Great customer service and amazing products!',
					'author'   => 'Mere W.',
					'location' => 'Suva, Fiji',
					'avatar'   => 'sun',
				),
			),
			'help'      => array(
				array(
					'icon'  => 'phone',
					'title' => 'Need help with your order?',
					'text'  => 'Call or message us on Viber. We are here in Fiji.',
				),
				array(
					'icon'  => 'chat',
					'title' => 'Message us on Viber',
					'text'  => '[phone]',
				),
				array(
					'icon'  => 'pin',
					'title' => 'Fiji based support',
					'text'  => 'Local team here to help you.',
				),
			),
		),
	);

	/**
	 * Filters the homepage copy.
	 *
	 * @param array $home Settings and blocks.
	 */
	return $home = apply_filters( 'medzuro_home', $home );
}

/**
 * A homepage setting.
 *
 * @param string $key     Setting key.
 * @param mixed  $default Fallback when unset.
 * @return mixed
 */
function medzuro_home_setting( $key, $default = '' ) {
	$settings = medzuro_home()['settings'];

	return ( isset( $settings[ $key ] ) && '' !== $settings[ $key ] ) ? $settings[ $key ] : $default;
}

/**
 * Homepage blocks of one type, in order.
 *
 * @param string $type Block type, e.g. 'trust'.
 * @return array<int,array>
 */
function medzuro_home_blocks( $type ) {
	return medzuro_home()['blocks'][ $type ] ?? array();
}
