<?php
/**
 * Homepage line icons.
 *
 * Generated by tools/export_ref_icons.py from
 * snippets/medzuro-ref-icon.liquid, which was a Liquid case statement over
 * 14 icon names. Path data is verbatim; only the <svg> wrapper is rebuilt
 * so every icon shares one set of attributes.
 *
 * @package Medzuro
 */

defined( 'ABSPATH' ) || exit;

/**
 * Echo a homepage icon.
 *
 * @param string $name Icon name, e.g. 'truck'.
 */
function medzuro_ref_icon( $name ) {
	$paths = medzuro_ref_icon_paths();

	if ( ! isset( $paths[ $name ] ) ) {
		return;
	}

	printf(
		'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">%s</svg>',
		wp_kses( $paths[ $name ], medzuro_svg_allowed_tags() )
	);
}

/**
 * Icon path data.
 *
 * @return array<string,string>
 */
function medzuro_ref_icon_paths() {
	return array(
		'truck'   => '<path d="M3 7h10v8H3z"/><path d="M13 10h4l3 3.2V15h-7z"/><circle cx="7" cy="17.3" r="1.7"/><circle cx="16.7" cy="17.3" r="1.7"/>',
		'pin'     => '<path d="M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="2.6"/>',
		'shield'  => '<path d="M12 3 5 6v5.5c0 4.3 2.9 7.4 7 8.9 4.1-1.5 7-4.6 7-8.9V6l-7-3Z"/><path d="m9 12 2 2 4-4"/>',
		'headset' => '<path d="M4 13a8 8 0 0 1 16 0"/><path d="M4 13v3a2 2 0 0 0 2 2h1v-5H6a2 2 0 0 0-2 2Z"/><path d="M20 13v3a2 2 0 0 1-2 2h-1v-5h1a2 2 0 0 1 2 2Z"/>',
		'phone'   => '<path d="M6.5 3.5h3l1.5 4-2 1.4a12 12 0 0 0 6.1 6.1l1.4-2 4 1.5v3a2 2 0 0 1-2.2 2A17 17 0 0 1 4.5 5.7a2 2 0 0 1 2-2.2Z"/>',
		'chat'    => '<path d="M20 12a7.5 7.5 0 0 1-10.9 6.7L4 20l1.3-4.1A7.5 7.5 0 1 1 20 12Z"/>',
		'globe'   => '<circle cx="12" cy="12" r="9"/><path d="M3 12h18"/><path d="M12 3a14 14 0 0 1 0 18"/><path d="M12 3a14 14 0 0 0 0 18"/>',
		'users'   => '<circle cx="9" cy="8" r="3"/><path d="M3.5 19a5.5 5.5 0 0 1 11 0"/><path d="M15 6.5a2.8 2.8 0 0 1 0 5.5"/><path d="M16.5 14a5 5 0 0 1 4 5"/>',
		'lab'     => '<path d="M9 3h6"/><path d="M10 3v5.2L5.6 17A2 2 0 0 0 7.4 20h9.2a2 2 0 0 0 1.8-3L14 8.2V3"/><path d="M8 14.5h8"/>',
		'puzzle'  => '<path d="M9 3a3 3 0 0 1 6 0v3h3a3 3 0 1 1 0 6h-3v3h-3a3 3 0 1 1-6 0H3v-6h3a3 3 0 1 0 0-6h3Z"/>',
		'package' => '<path d="m12 3 8 4.4v9.2L12 21l-8-4.4V7.4L12 3Z"/><path d="m4.6 7.7 7.4 4.2 7.4-4.2"/><path d="M12 12v8.5"/>',
		'leaf'    => '<path d="M20 4c0 9-5.5 14-12 14a6 6 0 0 1 0-12c4 0 6.5-1 12-2Z"/><path d="M4 20c4-6 8-9 14-12"/>',
		'award'   => '<circle cx="12" cy="9" r="5.5"/><path d="m8.5 13.5-1.5 7 5-2.5 5 2.5-1.5-7"/>',
		'clock'   => '<circle cx="12" cy="12" r="9"/><path d="M12 7v5.3l3.4 2"/>',
	);
}
