<?php'
/**'
 * Product page — marketing sections below the buybox.'
 *'
 * Generated from sections/medzuro-product-page.liquid (lines 270-460) by'
 * tools/port_section.py, then hand-finished for the product description.'
 * Static copy was inlined from templates/product.json at port time.'
 *'
 * @package Medzuro'
 */'
'
defined( 'ABSPATH' ) || exit;'
'
global $product;'
?>'
  <div class="mz-pdp-section mz-pdp-usage">'
    <div class="mz-pdp-shell">'
      <div class="mz-pdp-section-head">'
        <p>Way To Get The Best Results</p>'
        <h2>Make it part of your daily wellness routine</h2>'
      </div>'
      <div class="mz-pdp-usage-grid">'
        <div>'
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v18"/><path d="M6 9h12"/><path d="M8 21h8"/><path d="M9 3h6"/></svg>'
          <h3>Daily Serving</h3>'
          <p>Follow the product label or your practitioner's advice for the right daily serving.</p>'
        </div>'
        <div>'
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 2h10"/><path d="M9 2v6l-5 9a3 3 0 0 0 2.6 4.5h10.8A3 3 0 0 0 20 17L15 8V2"/><path d="M8 14h8"/></svg>'
          <h3>Simple Routine</h3>'
          <p>Take consistently with water or as recommended for your selected supplement.</p>'
        </div>'
        <div>'
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2a10 10 0 1 0 10 10"/><path d="M12 6v6l4 2"/></svg>'
          <h3>Consistency</h3>'
          <p>Best results come from a steady routine, balanced meals, rest, and hydration.</p>'
        </div>'
      </div>'
    </div>'
  </div>'
'
  <div class="mz-pdp-section mz-pdp-solutions">'
    <div class="mz-pdp-shell">'
      <div class="mz-pdp-section-head">'
        <p>Choose Your Solution</p>'
        <h2>Chosen Together For Better Results</h2>'
      </div>'
      <div class="mz-pdp-solution-grid">'
        <article>'
          <span class="mz-pdp-mini-bottle mz-pdp-mini-bottle--1" aria-hidden="true"><span></span></span>'
          <div>'
            <h3>HolyOak Ashwagandha</h3>'
            <p>Stress balance, daily energy, and recovery support.</p>'
            <strong>FJD $39.20</strong>'
          </div>'
          <a href="<?php echo esc_url( get_permalink( get_page_by_path( 'contact' ) ) ); ?>">Add +</a>
        </article>'
        <article>'
          <span class="mz-pdp-mini-bottle mz-pdp-mini-bottle--3" aria-hidden="true"><span></span></span>'
          <div>'
            <h3>HolyOak Turmeric Curcumin</h3>'
            <p>Joint comfort and daily antioxidant support.</p>'
            <strong>FJD $38.25</strong>'
          </div>'
          <a href="<?php echo esc_url( get_permalink( get_page_by_path( 'contact' ) ) ); ?>">Add +</a>
        </article>'
        <article>'
          <span class="mz-pdp-mini-bottle mz-pdp-mini-bottle--5" aria-hidden="true"><span></span></span>'
          <div>'
            <h3>HolyOak Multivitamin</h3>'
            <p>Daily wellness support for busy routines.</p>'
            <strong>FJD $35.00</strong>'
          </div>'
          <a href="<?php echo esc_url( get_permalink( get_page_by_path( 'contact' ) ) ); ?>">Add +</a>
        </article>'
      </div>'
    </div>'
  </div>'
'
  <div class="mz-pdp-section mz-pdp-purity">'
    <div class="mz-pdp-shell mz-pdp-purity__inner">'
      <div class="mz-pdp-purity__copy">'
        <p>Lab Tested. Pure. Safe. Trusted.</p>'
        <h2>Lab tested quality you can trust</h2>'
        <span>Selected HolyOak products are backed by independent testing standards for purity, potency, and safety.</span>'
        <div class="mz-pdp-purity-list">'
          <div>Purity checked</div>'
          <div>Potency verified</div>'
          <div>Quality assured</div>'
          <div>Global lab standards</div>'
        </div>'
      </div>'
      <img src="<?php echo esc_url( get_template_directory_uri() . '/assets/img/medzuro-lab-trust.png' ); ?>" alt="" loading="lazy" width="780" height="520">'
    </div>'
  </div>'
'
  <div class="mz-pdp-section mz-pdp-difference">'
    <div class="mz-pdp-shell">'
      <div class="mz-pdp-section-head">'
        <p>Daily Wellness</p>'
        <h2>Feel The Difference Consistent Support Can Make</h2>'
      </div>'
      <div class="mz-pdp-difference-grid">'
        <article>'
          <span>01</span>'
          <h3>More Energy</h3>'
          <p>Supports everyday vitality so your routine feels lighter and more consistent.</p>'
        </article>'
        <article>'
          <span>02</span>'
          <h3>Better Recovery</h3>'
          <p>Useful for active lifestyles, long workdays, and post-workout recovery habits.</p>'
        </article>'
        <article>'
          <span>03</span>'
          <h3>Daily Balance</h3>'
          <p>Helps build a dependable wellness rhythm when taken as part of a balanced routine.</p>'
        </article>'
        <article>'
          <span>04</span>'
          <h3>Confidence</h3>'
          <p>Genuine products, local support, and clear quality standards make reordering simple.</p>'
        </article>'
      </div>'
    </div>'
  </div>'
'
  <div class="mz-pdp-section mz-pdp-reviews">'
    <div class="mz-pdp-shell">'
      <div class="mz-pdp-section-head">'
        <p>Community</p>'
        <h2>What Fiji Customers Are Saying</h2>'
      </div>'
      <div class="mz-pdp-review-grid">'
        <article>'
          <span aria-hidden="true">&#9733;&#9733;&#9733;&#9733;&#9733;</span>'
          <p>Excellent quality products and fast delivery. I have been using HolyOak supplements for months.</p>'
          <strong>Sarah L.</strong>'
          <small>Suva, Fiji</small>'
        </article>'
        <article>'
          <span aria-hidden="true">&#9733;&#9733;&#9733;&#9733;&#9733;</span>'
          <p>Genuine products you can trust. I like that the brand takes lab testing seriously.</p>'
          <strong>Rajesh K.</strong>'
          <small>Nausori, Fiji</small>'
        </article>'
        <article>'
          <span aria-hidden="true">&#9733;&#9733;&#9733;&#9733;&#9733;</span>'
          <p>Same-day delivery in Suva is a real plus. Great customer support and clear communication.</p>'
          <strong>Mere W.</strong>'
          <small>Suva, Fiji</small>'
        </article>'
      </div>'
    </div>'
  </div>'
'
  <div class="mz-pdp-section mz-pdp-inside">'
    <div class="mz-pdp-shell mz-pdp-inside__inner">'
      <div>'
        <p>What's Inside</p>'
        <h2>Clean wellness support, clearly selected</h2>'
        <?php if ( $product && $product->get_description() ) : ?>'
          <div class="rte"><?php echo wp_kses_post( wpautop( $product->get_description() ) ); ?></div>'
        <?php else : ?>'
          <span>Medzuro Retail focuses on genuine products, clear quality standards, and local access for Fiji customers.</span>'
        <?php endif; ?>'
      </div>'
      <div class="mz-pdp-inside-card">'
        <h3>Quality Promise</h3>'
        <ul>'
          <li>Selected HolyOak wellness products</li>'
          <li>Batch testing and quality review</li>'
          <li>No unnecessary fillers in selected ranges</li>'
          <li>Available locally through Medzuro Retail</li>'
        </ul>'
        <a href="<?php echo esc_url( get_permalink( get_page_by_path( 'lab-test-and-purity' ) ) ); ?>">View Quality Testing</a>
      </div>'
    </div>'
  </div>'
'
  <div class="mz-pdp-section mz-pdp-faq">'
    <div class="mz-pdp-shell">'
      <div class="mz-pdp-section-head">'
        <p>FAQ</p>'
        <h2>The Doubts In Your Head, Answered</h2>'
      </div>'
      <div class="mz-pdp-faq-list">'
        <details open>'
          <summary>Are these genuine HolyOak products?</summary>'
          <p>Yes. Medzuro Retail offers selected HolyOak products locally in Fiji with customer support you can reach.</p>'
        </details>'
        <details>'
          <summary>How soon can I get delivery?</summary>'
          <p>Delivery timing depends on your location. Same-day delivery is available in most of Suva when stock and cut-off timing allow.</p>'
        </details>'
        <details>'
          <summary>Can I pick up locally?</summary>'
          <p>Yes. Local pickup can be arranged from the Suva location. Contact the team before visiting so stock can be confirmed.</p>'
        </details>'
        <details>'
          <summary>How do I know the product is tested?</summary>'
          <p>HolyOak products are independently tested for quality, purity, and potency. You can review more on the Lab Test and Purity page.</p>'
        </details>'
      </div>'
    </div>'
  </div>'
