#!/usr/bin/env python3
"""Emit inc/ref-icons.php from snippets/medzuro-ref-icon.liquid.

The homepage icons were a Liquid {% case %} over 14 names. Transcribing SVG
path data by hand invites typos that are invisible until rendered, so this
lifts them verbatim.

Usage:
  python tools/export_ref_icons.py
"""

import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent.parent
SNIPPET = HERE.parent / "medzuro" / "snippets" / "medzuro-ref-icon.liquid"


def main():
    text = SNIPPET.read_text(encoding="utf-8")

    # {%- when 'name' -%}<svg ...>...</svg>
    pairs = re.findall(
        r"\{%-?\s*when\s+'([a-z_]+)'\s*-?%\}\s*(<svg.*?</svg>)",
        text,
        flags=re.S,
    )

    if not pairs:
        raise SystemExit("no icons found — did the snippet format change?")

    width = max(len(name) for name, _ in pairs) + 2

    rows = []
    for name, svg in pairs:
        # Keep only the inner shapes; the wrapper is rebuilt in PHP so every
        # icon shares one set of attributes.
        inner = re.sub(r"^<svg[^>]*>|</svg>$", "", svg.strip())
        inner = inner.replace("\\", "\\\\").replace("'", "\\'")
        rows.append(f"\t\t{repr_key(name):<{width}} => '{inner}',")

    body = "\n".join(rows)

    php = f"""<?php
/**
 * Homepage line icons.
 *
 * Generated by tools/export_ref_icons.py from
 * snippets/medzuro-ref-icon.liquid, which was a Liquid case statement over
 * {len(pairs)} icon names. Path data is verbatim; only the <svg> wrapper is rebuilt
 * so every icon shares one set of attributes.
 *
 * @package Medzuro
 */

defined( 'ABSPATH' ) || exit;

/**
 * Echo a homepage icon.
 *
 * @param string $name Icon name, e.g. 'truck'.
 */
function medzuro_ref_icon( $name ) {{
\t$paths = medzuro_ref_icon_paths();

\tif ( ! isset( $paths[ $name ] ) ) {{
\t\treturn;
\t}}

\tprintf(
\t\t'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">%s</svg>',
\t\twp_kses( $paths[ $name ], medzuro_svg_allowed_tags() )
\t);
}}

/**
 * Icon path data.
 *
 * @return array<string,string>
 */
function medzuro_ref_icon_paths() {{
\treturn array(
{body}
\t);
}}
"""

    out = HERE / "inc" / "ref-icons.php"
    out.write_text(php, encoding="utf-8")

    print(f"  -> inc/ref-icons.php ({len(pairs)} icons)")
    print("     " + ", ".join(name for name, _ in pairs))


def repr_key(key):
    return "'" + key + "'"


if __name__ == "__main__":
    main()
