#!/usr/bin/env python3
"""Emit inc/home-content.php from the Shopify homepage template.

The home section was block-driven: 25 blocks across 6 types, ordered by
block_order, plus ~35 section settings. Rather than hand-transcribe them into
PHP, this reads templates/index.json and writes the array, so the copy on the
WordPress site provably matches what the Shopify storefront rendered.

Usage:
  python tools/export_home_content.py
"""

import json
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent.parent
SHOPIFY = HERE.parent / "medzuro"
SECTION = "medzuro-reference-home"


def php_value(value, indent):
    """Render a Python value as PHP source."""
    pad = "\t" * indent

    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if value is None:
        return "''"
    if isinstance(value, list):
        if not value:
            return "array()"
        inner = ",\n".join(
            f"{pad}\t{php_value(v, indent + 1)}" for v in value
        )
        return "array(\n" + inner + ",\n" + pad + ")"
    if isinstance(value, dict):
        if not value:
            return "array()"
        width = max(len(k) for k in value) + 2
        inner = ",\n".join(
            f"{pad}\t{repr_key(k):<{width}} => {php_value(v, indent + 1)}"
            for k, v in value.items()
        )
        return "array(\n" + inner + ",\n" + pad + ")"

    return "'" + str(value).replace("\\", "\\\\").replace("'", "\\'") + "'"


def repr_key(key):
    return "'" + str(key).replace("'", "\\'") + "'"


def main():
    raw = (SHOPIFY / "templates" / "index.json").read_text(encoding="utf-8-sig")
    blob = json.loads(re.sub(r"/\*.*?\*/", "", raw, flags=re.S))

    section = next(
        s for s in blob["sections"].values() if s.get("type") == SECTION
    )

    settings = section.get("settings") or {}
    blocks = section.get("blocks") or {}
    order = section.get("block_order") or list(blocks)

    grouped = {}
    for block_id in order:
        block = blocks[block_id]
        grouped.setdefault(block["type"], []).append(block.get("settings") or {})

    content = {"settings": settings, "blocks": grouped}

    body = php_value(content, 1)

    php = f"""<?php
/**
 * Homepage copy.
 *
 * Generated by tools/export_home_content.py from the Shopify
 * templates/index.json, so it matches what the storefront rendered. The
 * homepage section was block-driven ({len(order)} blocks across
 * {len(grouped)} types); blocks are grouped by type here, in block_order.
 *
 * Regenerate rather than editing by hand while the Shopify theme is still the
 * source of truth. Once it is not, edit freely and drop the generator.
 *
 * @package Medzuro
 */

defined( 'ABSPATH' ) || exit;

/**
 * Homepage settings and blocks.
 *
 * @return array
 */
function medzuro_home() {{
\tstatic $home = null;

\tif ( null !== $home ) {{
\t\treturn $home;
\t}}

\t$home = {body};

\t/**
\t * Filters the homepage copy.
\t *
\t * @param array $home Settings and blocks.
\t */
\treturn $home = apply_filters( 'medzuro_home', $home );
}}

/**
 * A homepage setting.
 *
 * @param string $key     Setting key.
 * @param mixed  $default Fallback when unset.
 * @return mixed
 */
function medzuro_home_setting( $key, $default = '' ) {{
\t$settings = medzuro_home()['settings'];

\treturn ( isset( $settings[ $key ] ) && '' !== $settings[ $key ] ) ? $settings[ $key ] : $default;
}}

/**
 * Homepage blocks of one type, in order.
 *
 * @param string $type Block type, e.g. 'trust'.
 * @return array<int,array>
 */
function medzuro_home_blocks( $type ) {{
\treturn medzuro_home()['blocks'][ $type ] ?? array();
}}
"""

    out = HERE / "inc" / "home-content.php"
    out.write_text(php, encoding="utf-8")

    print(f"  -> inc/home-content.php")
    print(f"     {len(settings)} settings, {len(order)} blocks")
    for name, items in grouped.items():
        print(f"       {name}: {len(items)}")


if __name__ == "__main__":
    main()
